// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimTaskReducer from "../claim_task_reducer";
import CreateRoomReducer from "../create_room_reducer";
import HeartbeatAgentReducer from "../heartbeat_agent_reducer";
import HeartbeatOperatorReducer from "../heartbeat_operator_reducer";
import HumanOverrideReducer from "../human_override_reducer";
import IssueOrderReducer from "../issue_order_reducer";
import JoinRoomReducer from "../join_room_reducer";
import PostResultReducer from "../post_result_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import ResolveCrisisReducer from "../resolve_crisis_reducer";
import SubmitDraftReducer from "../submit_draft_reducer";
import SubmitGoalReducer from "../submit_goal_reducer";

export type ClaimTaskParams = __Infer<typeof ClaimTaskReducer>;
export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type HeartbeatAgentParams = __Infer<typeof HeartbeatAgentReducer>;
export type HeartbeatOperatorParams = __Infer<typeof HeartbeatOperatorReducer>;
export type HumanOverrideParams = __Infer<typeof HumanOverrideReducer>;
export type IssueOrderParams = __Infer<typeof IssueOrderReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type PostResultParams = __Infer<typeof PostResultReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type ResolveCrisisParams = __Infer<typeof ResolveCrisisReducer>;
export type SubmitDraftParams = __Infer<typeof SubmitDraftReducer>;
export type SubmitGoalParams = __Infer<typeof SubmitGoalReducer>;

