// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  goalId: __t.u64().name("goal_id"),
  nodeKey: __t.string().name("node_key"),
  name: __t.string(),
  kind: __t.string(),
  lane: __t.string(),
  owner: __t.string(),
  status: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  adjacentKeys: __t.string().name("adjacent_keys"),
  fortification: __t.i32(),
  bluePressure: __t.i32().name("blue_pressure"),
  redPressure: __t.i32().name("red_pressure"),
  hqIntegrity: __t.i32().name("hq_integrity"),
  updatedAt: __t.timestamp().name("updated_at"),
});
