// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  goalId: __t.option(__t.u64()).name("goal_id"),
  taskId: __t.option(__t.u64()).name("task_id"),
  agentId: __t.option(__t.u64()).name("agent_id"),
  operatorId: __t.option(__t.identity()).name("operator_id"),
  kind: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
