// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  roomId: __t.u64().name("room_id"),
  displayName: __t.string().name("display_name"),
  team: __t.string(),
  ready: __t.bool(),
  selectedTaskId: __t.option(__t.u64()).name("selected_task_id"),
  lastHeartbeat: __t.timestamp().name("last_heartbeat"),
});
