// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  goalId: __t.u64().primaryKey().name("goal_id"),
  roomId: __t.u64().name("room_id"),
  points: __t.i64(),
  validResults: __t.u32().name("valid_results"),
  lateResults: __t.u32().name("late_results"),
  invalidResults: __t.u32().name("invalid_results"),
  humanOverrides: __t.u32().name("human_overrides"),
  estimatedCostMicros: __t.u64().name("estimated_cost_micros"),
});
