// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  goalId: __t.u64().name("goal_id"),
  team: __t.string(),
  supplyMicros: __t.u64().name("supply_micros"),
  morale: __t.i32(),
  commandTokens: __t.i32().name("command_tokens"),
  hqIntegrity: __t.i32().name("hq_integrity"),
  status: __t.string(),
  updatedAt: __t.timestamp().name("updated_at"),
});
