// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  owner: __t.identity(),
  name: __t.string(),
  model: __t.string(),
  role: __t.string(),
  team: __t.string(),
  status: __t.string(),
  currentTaskId: __t.option(__t.u64()).name("current_task_id"),
  latestThought: __t.string().name("latest_thought"),
  conn: __t.option(__t.connectionId()),
  lastHeartbeat: __t.timestamp().name("last_heartbeat"),
});
