// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  goalId: __t.u64().name("goal_id"),
  team: __t.string(),
  targetNodeId: __t.u64().name("target_node_id"),
  orderType: __t.string().name("order_type"),
  priority: __t.u32(),
  status: __t.string(),
  issuedBy: __t.identity().name("issued_by"),
  createdAt: __t.timestamp().name("created_at"),
  expiresAtMicros: __t.u64().name("expires_at_micros"),
});
