// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  roomId: __t.u64().name("room_id"),
  goalId: __t.u64().name("goal_id"),
  parentId: __t.option(__t.u64()).name("parent_id"),
  title: __t.string(),
  status: __t.string(),
  requiredRole: __t.string().name("required_role"),
  depth: __t.u32(),
  attempts: __t.u32(),
  assignedAgentId: __t.option(__t.u64()).name("assigned_agent_id"),
  assignedModel: __t.option(__t.string()).name("assigned_model"),
  claimedAt: __t.option(__t.timestamp()).name("claimed_at"),
  deadlineMs: __t.u64().name("deadline_ms"),
  result: __t.option(__t.string()),
  risk: __t.option(__t.string()),
  confidence: __t.option(__t.string()),
  latencyMs: __t.u32().name("latency_ms"),
  costMicros: __t.u64().name("cost_micros"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
