// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  id: __t.u64(),
  roomId: __t.u64(),
  owner: __t.identity(),
  name: __t.string(),
  model: __t.string(),
  role: __t.string(),
  team: __t.string(),
  status: __t.string(),
  currentTaskId: __t.option(__t.u64()),
  latestThought: __t.string(),
  conn: __t.option(__t.connectionId()),
  lastHeartbeat: __t.timestamp(),
});
export type Agent = __Infer<typeof Agent>;

export const BattleNode = __t.object("BattleNode", {
  id: __t.u64(),
  roomId: __t.u64(),
  goalId: __t.u64(),
  nodeKey: __t.string(),
  name: __t.string(),
  kind: __t.string(),
  lane: __t.string(),
  owner: __t.string(),
  status: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  adjacentKeys: __t.string(),
  fortification: __t.i32(),
  bluePressure: __t.i32(),
  redPressure: __t.i32(),
  hqIntegrity: __t.i32(),
  updatedAt: __t.timestamp(),
});
export type BattleNode = __Infer<typeof BattleNode>;

export const BattleOrder = __t.object("BattleOrder", {
  id: __t.u64(),
  roomId: __t.u64(),
  goalId: __t.u64(),
  team: __t.string(),
  targetNodeId: __t.u64(),
  orderType: __t.string(),
  priority: __t.u32(),
  status: __t.string(),
  issuedBy: __t.identity(),
  createdAt: __t.timestamp(),
  expiresAtMicros: __t.u64(),
});
export type BattleOrder = __Infer<typeof BattleOrder>;

export const BattleTimer = __t.object("BattleTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type BattleTimer = __Infer<typeof BattleTimer>;

export const CrewSlot = __t.object("CrewSlot", {
  id: __t.u64(),
  roomId: __t.u64(),
  goalId: __t.u64(),
  role: __t.string(),
  team: __t.string(),
  model: __t.string(),
  count: __t.u32(),
});
export type CrewSlot = __Infer<typeof CrewSlot>;

export const CrewSpec = __t.object("CrewSpec", {
  model: __t.string(),
  role: __t.string(),
  count: __t.u32(),
});
export type CrewSpec = __Infer<typeof CrewSpec>;

export const Crisis = __t.object("Crisis", {
  id: __t.u64(),
  roomId: __t.u64(),
  goalId: __t.u64(),
  kind: __t.string(),
  message: __t.string(),
  status: __t.string(),
  choice: __t.i32(),
  createdAt: __t.timestamp(),
  deadlineMicros: __t.u64(),
});
export type Crisis = __Infer<typeof Crisis>;

export const CrisisTimer = __t.object("CrisisTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CrisisTimer = __Infer<typeof CrisisTimer>;

export const DraftSlot = __t.object("DraftSlot", {
  id: __t.u64(),
  roomId: __t.u64(),
  team: __t.string(),
  role: __t.string(),
  model: __t.string(),
  count: __t.u32(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type DraftSlot = __Infer<typeof DraftSlot>;

export const Event = __t.object("Event", {
  id: __t.u64(),
  roomId: __t.u64(),
  goalId: __t.option(__t.u64()),
  taskId: __t.option(__t.u64()),
  agentId: __t.option(__t.u64()),
  operatorId: __t.option(__t.identity()),
  kind: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp(),
});
export type Event = __Infer<typeof Event>;

export const Goal = __t.object("Goal", {
  id: __t.u64(),
  roomId: __t.u64(),
  title: __t.string(),
  status: __t.string(),
  maxDepth: __t.u32(),
  maxTasks: __t.u32(),
  deadlineMs: __t.u64(),
  runBudgetMicros: __t.u64(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
});
export type Goal = __Infer<typeof Goal>;

export const Operator = __t.object("Operator", {
  identity: __t.identity(),
  roomId: __t.u64(),
  displayName: __t.string(),
  team: __t.string(),
  ready: __t.bool(),
  selectedTaskId: __t.option(__t.u64()),
  lastHeartbeat: __t.timestamp(),
});
export type Operator = __Infer<typeof Operator>;

export const ReaperTimer = __t.object("ReaperTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ReaperTimer = __Infer<typeof ReaperTimer>;

export const Room = __t.object("Room", {
  id: __t.u64(),
  name: __t.string(),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  status: __t.string(),
});
export type Room = __Infer<typeof Room>;

export const Score = __t.object("Score", {
  goalId: __t.u64(),
  roomId: __t.u64(),
  points: __t.i64(),
  validResults: __t.u32(),
  lateResults: __t.u32(),
  invalidResults: __t.u32(),
  humanOverrides: __t.u32(),
  estimatedCostMicros: __t.u64(),
});
export type Score = __Infer<typeof Score>;

export const Task = __t.object("Task", {
  id: __t.u64(),
  roomId: __t.u64(),
  goalId: __t.u64(),
  parentId: __t.option(__t.u64()),
  title: __t.string(),
  status: __t.string(),
  requiredRole: __t.string(),
  depth: __t.u32(),
  attempts: __t.u32(),
  assignedAgentId: __t.option(__t.u64()),
  assignedModel: __t.option(__t.string()),
  claimedAt: __t.option(__t.timestamp()),
  deadlineMs: __t.u64(),
  result: __t.option(__t.string()),
  risk: __t.option(__t.string()),
  confidence: __t.option(__t.string()),
  team: __t.string(),
  targetNodeId: __t.option(__t.u64()),
  actionType: __t.string(),
  priority: __t.u32(),
  latencyMs: __t.u32(),
  costMicros: __t.u64(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Task = __Infer<typeof Task>;

export const TeamState = __t.object("TeamState", {
  id: __t.u64(),
  roomId: __t.u64(),
  goalId: __t.u64(),
  team: __t.string(),
  supplyMicros: __t.u64(),
  morale: __t.i32(),
  commandTokens: __t.i32(),
  hqIntegrity: __t.i32(),
  status: __t.string(),
  updatedAt: __t.timestamp(),
});
export type TeamState = __Infer<typeof TeamState>;

export const WorkerResult = __t.object("WorkerResult", {
  outcome: __t.string(),
  result: __t.string(),
  children: __t.array(__t.string()),
  risk: __t.string(),
  confidence: __t.string(),
});
export type WorkerResult = __Infer<typeof WorkerResult>;

